name: frontend
description: "VibeQuest: Anime & Game OST Finder"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # HTTP & API
  dio: ^5.4.0
  
  # Audio Recording
  record: ^5.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  
  # Audio Playing (optional)
  audioplayers: ^5.2.1
  
  # State Management
  provider: ^6.1.1
  
  # URL Launcher
  url_launcher: ^6.2.2
  
  # Google Fonts
  google_fonts: ^6.1.0

dependency_overrides:
  record_linux: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
