name: frontend
description: "OtoKage: Anime Music Recognition"
publish_to: 'none'
version: 1.3.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # HTTP & API
  dio: ^5.4.0
  
  # Audio Recording
  record: ^5.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  
  # Audio Playing (optional)
  audioplayers: ^5.2.1
  
  # State Management
  provider: ^6.1.1
  
  # URL Launcher
  url_launcher: ^6.2.2
  
  # Google Fonts & Auth
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2

dependency_overrides:
  record_linux: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  image: ^4.1.7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_native_splash:
  color: "#0B0D14"
  color_dark: "#0B0D14"
  android_12:
    color: "#0B0D14"
    icon_background_color: "#0B0D14"
  android: true
  ios: true
  web: true

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "#00E5FF"
  adaptive_icon_foreground: "assets/otokage_icon.png"
  background_color_ios: "#0B0D14"
  image_path: "assets/otokage_icon.png"
  min_sdk_android: 21
